# Generated by Django 4.2.27 on 2025-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
