# Generated by Django 4.2.27 on 2025-12-05 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_posts', '0002_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votos',
            field=models.ManyToManyField(blank=True, related_name='voted_posts', through='app_posts.Voto', to=settings.AUTH_USER_MODEL),
        ),
    ]
