# Generated by Django 4.2.27 on 2025-12-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0003_post_votos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='votos',
            new_name='voto_totales',
        ),
        migrations.AlterField(
            model_name='voto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='app_posts.post'),
        ),
    ]
