# Generated by Django 4.2.27 on 2025-12-09 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_posts', '0004_rename_votos_post_voto_totales_alter_voto_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='tipo_voto',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='fecha_voto',
        ),
        migrations.AddField(
            model_name='post',
            name='voto_valor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_posts.post'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
