# Generated by Django 6.0 on 2025-12-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0005_rename_tipo_voto_voto_value_remove_voto_fecha_voto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='voto',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together={('usuario', 'post')},
        ),
        migrations.AddField(
            model_name='voto',
            name='valor',
            field=models.IntegerField(choices=[(1, 'Upvoto'), (-1, 'Downvoto')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, editable=False, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='voto_totales',
            field=models.ManyToManyField(blank=True, editable=False, related_name='voted_posts', through='app_posts.Voto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='voto_valor',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='voto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='app_posts.post'),
        ),
        migrations.RemoveField(
            model_name='voto',
            name='value',
        ),
    ]
