# Generated by Django 6.0 on 2025-12-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0006_rename_user_voto_usuario_alter_voto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_posts.post'),
        ),
    ]
